version: "3.7"


services:
  #MYSQL --------------------------------
  mysql-server:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - 3307:3306 
    environment:
        MYSQL_DATABASE: 'pregunta3'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true' 
  
  #MONGO --------------------------------
  
  mongo-server: 
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017" 


  #REDIS ---------------------------
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
    - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"